# Generated by Django 5.1.6 on 2025-03-10 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('createAt', models.DateTimeField(auto_now_add=True)),
                ('createdBy', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=200)),
                ('image', models.ImageField(upload_to='static/images')),
                ('content', models.TextField()),
                ('published', models.BooleanField(default=False)),
                ('tags', models.CharField(max_length=20)),
                ('createAt', models.DateTimeField(auto_now_add=True)),
                ('createdBy', models.IntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.category')),
            ],
            options={
                'verbose_name_plural': 'Posts',
            },
        ),
    ]
