# Generated by Django 5.1.6 on 2025-03-16 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='updatedBy',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
