# Generated by Django 5.1.6 on 2025-03-17 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_category_updatedby'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='updatedBy',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
